import chalk from 'chalk';
import { ReviewResult } from './types.js';

export class ReviewFormatter {
  formatTerminal(result: ReviewResult): void {
    const scoreColor = result.score >= 80 ? chalk.green :
                       result.score >= 60 ? chalk.yellow : chalk.red;

    console.log(chalk.bold(`\nCode Review: ${result.filePath}`));
    console.log(chalk.dim(`Date: ${result.date} | Model: ${result.model}`));
    console.log(scoreColor(`\nQuality Score: ${result.score}/100`));

    if (result.issues.length > 0) {
      console.log(chalk.red('\nIssues Found:'));
      result.issues.forEach(issue => {
        const icon = issue.severity === 'critical' ? chalk.red('CRT') :
                     issue.severity === 'medium' ? chalk.yellow('MED') : chalk.dim('MIN');
        const lineInfo = issue.line ? chalk.dim(` (line ${issue.line})`) : '';
        console.log(`  [${icon}] ${issue.message}${lineInfo}`);
      });
    } else {
      console.log(chalk.green('\nNo issues found!'));
    }

    if (result.suggestions.length > 0) {
      console.log(chalk.blue('\nSuggestions:'));
      result.suggestions.forEach(s => console.log(`  - ${s}`));
    }

    if (result.patternsFollowed.length > 0) {
      console.log(chalk.green('\nPatterns Followed:'));
      result.patternsFollowed.forEach(p => console.log(chalk.dim(`  - ${p}`)));
    }
  }

  formatMarkdown(result: ReviewResult, fullReviewText: string): string {
    return `# Code Review: ${result.filePath}

**Date:** ${result.date}
**Model:** ${result.model}
**Quality Score:** ${result.score}/100

${fullReviewText}

---
*Generated by DevPilot*
`;
  }
}
